default: &default
  adapter: postgresql
  encoding: unicode
  host: "34.95.239.203"
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: gcp_rails_test_development

production:
  <<: *default
  database: gcloud-rails-test-production