default: &default
  adapter: postgresql
  encoding: unicode
  host: "34.95.239.203"
  username: postgres
  password: gcloud-rails-test-production
  pool: 5

development:
  <<: *default
  database: gcloud-rails-test-production

production:
  <<: *default
  database: gcloud-rails-test-production